// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQTblr0XeEuzwWczOzgwHcWuIexeG85A',
    appId: '1:81894199230:android:4f8602fad0eb8b325ab3ef',
    messagingSenderId: '81894199230',
    projectId: 'fi-a3-todo-application',
    storageBucket: 'fi-a3-todo-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9JrDo0CJvep_iTwG0LyFqZx-xO7cncrM',
    appId: '1:81894199230:ios:4c4cc441704c61045ab3ef',
    messagingSenderId: '81894199230',
    projectId: 'fi-a3-todo-application',
    storageBucket: 'fi-a3-todo-application.appspot.com',
    androidClientId: '81894199230-hkduru2v1isov3uahbhdc9qo9tj28n73.apps.googleusercontent.com',
    iosClientId: '81894199230-kqu75hskd8anvvagu4popu3vhd1kk56l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
